# Generated by Django 3.2.10 on 2022-01-01 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='Имя пользователя')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Имя и фамилия')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата регистрации')),
                ('is_staff', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Статус администратора')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название класса')),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Классы',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Тема')),
                ('first_information', models.TextField(verbose_name='Первая часть информация')),
                ('second_information', models.TextField(blank=True, null=True, verbose_name='Вторая часть информация')),
                ('third_information', models.TextField(blank=True, null=True, verbose_name='Третья часть информация')),
                ('released_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата анонсирование')),
                ('first_picture', models.ImageField(upload_to='images/', verbose_name='Первая картина')),
                ('second_picture', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Вторая картина')),
                ('third_picture', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Третья картина')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Статус', max_length=150)),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статус',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ManyToManyField(to='core.Group', verbose_name='Руководимые классы')),
                ('user', models.ForeignKey(help_text='Пользователь', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Учитель(-ница)')),
            ],
            options={
                'verbose_name': 'Учитель',
                'verbose_name_plural': 'Учителя',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.group', verbose_name='Класс ученика(-цы)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ученик(-ца)')),
            ],
            options={
                'verbose_name': 'Ученик(-ца)',
                'verbose_name_plural': 'Ученики',
            },
        ),
        migrations.CreateModel(
            name='Secret_key',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Придумайте код из 10-ти цифр', max_length=10, verbose_name='Ключ')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.group', verbose_name='Класс')),
            ],
            options={
                'verbose_name': 'Ключ для регистрации',
                'verbose_name_plural': 'Ключи для регистрации',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='related_students',
            field=models.ManyToManyField(related_name='students', to='core.Student', verbose_name='Ученики'),
        ),
        migrations.AddField(
            model_name='group',
            name='related_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teacher', to='core.teacher', verbose_name='Классный руководитель'),
        ),
        migrations.AddField(
            model_name='newuser',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.status', verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='newuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
