# Generated by Django 3.2.10 on 2022-01-01 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='related_students',
            field=models.ManyToManyField(blank=True, related_name='students', to='core.Student', verbose_name='Ученики'),
        ),
        migrations.AlterField(
            model_name='group',
            name='related_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teacher', to='core.teacher', verbose_name='Классный руководитель'),
        ),
    ]
