# Generated by Django 3.2.10 on 2022-01-01 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220101_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='related_teacher',
            new_name='teacher_user',
        ),
        migrations.RemoveField(
            model_name='group',
            name='related_students',
        ),
        migrations.AddField(
            model_name='group',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='related_students', to='core.Student', verbose_name='Ученики'),
        ),
    ]
