# Generated by Django 3.2.10 on 2022-01-02 12:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
