# Generated by Django 3.2.10 on 2022-01-02 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_test_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
