# Generated by Django 3.2.10 on 2022-01-03 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_teacher_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.ForeignKey(help_text='Пользователь', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Учитель(-ница)'),
        ),
        migrations.CreateModel(
            name='Head_teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ManyToManyField(to='core.Group', verbose_name='Руководимые классы')),
                ('subject', models.ManyToManyField(to='core.Subject', verbose_name='Предметы которые обучаете')),
                ('user', models.ForeignKey(help_text='Пользователь', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Завуч')),
            ],
            options={
                'verbose_name': 'Завуч',
                'verbose_name_plural': 'Завуч',
            },
        ),
    ]
