# Generated by Django 3.2.10 on 2022-01-03 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20220103_1219'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Head_teacher',
        ),
    ]
