# Generated by Django 3.2.10 on 2022-01-03 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_student_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='group',
            field=models.ManyToManyField(blank=True, to='core.Group', verbose_name='Руководимые классы'),
        ),
    ]
